### ISSUE TITLE
Sifive Core + nvdla all on VCU118

### ISSUE THREAD

**Issue by isuckatdrifting** [farzadfch/freedom#2]
Hello Mr.Farshchi,

  I saw that you have already put sifive core + nvdla on VCU118 on the sifive forum.
  I've got a pmod SDCard adapter for VCU118, and I've generated bit and mcs files from freedom **master** branch -- the **vcu118nvdla** makefile config. My question is that if I want to boot linux from SDCard, should I change any hardware (from scala) and make again?
  I've got no pcie or FMC connections by the way, just wanna see if only one board + usb connection could run the system.

  Thanks much!

**Comment by farzad64** [comment]
Sorry, I missed your question here. I tried to answer it on [SiFive's repository](https://github.com/sifive/freedom/issues/92).
